const T = {
  bg: "#0a0a0c",
  surf: "#131318",
  bdr: "#23232a",
  text: "#e5e5ea",
  body: "#b8b8c0",
  sub: "#8a8a92",
  meta: "#5a5a62",
  mono: "'IBM Plex Mono', ui-monospace, monospace",
  sans: "'IBM Plex Sans', system-ui, sans-serif",
  serif: "'DM Serif Display', Georgia, serif",
};

const FONTS = `@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@400;500;600&family=DM+Serif+Display:ital@0;1&display=swap');`;

export const metadata = {
  title: "Terms of Service — Writers Room",
};

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: T.bg, color: T.text, fontFamily: T.sans }}>
      <style>{FONTS}</style>
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "64px 24px 80px" }}>
        <a
          href="/"
          style={{ fontFamily: T.mono, fontSize: 11, color: T.meta, letterSpacing: "0.1em", textDecoration: "none", display: "inline-block", marginBottom: 40 }}
        >
          ← WRITERS ROOM
        </a>

        <h1 style={{ fontFamily: T.serif, fontSize: 36, fontWeight: 400, color: T.text, marginBottom: 8 }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: T.mono, fontSize: 11, color: T.meta, marginBottom: 48 }}>
          Last updated: June 2025
        </p>

        <Section title="Acceptance">
          By using Writers Room you agree to these terms. If you do not agree, do not use the service.
        </Section>

        <Section title="The Service">
          Writers Room is a writing collaboration tool that provides AI-assisted writing rooms, message history, and project folders. The service is provided as-is and may change or be discontinued at any time.
        </Section>

        <Section title="Your Account">
          <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must not share your account or invite codes with people outside your intended collaborators.</li>
            <li>You must be at least 13 years old to use the service.</li>
          </ul>
        </Section>

        <Section title="Your Content">
          <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
            <li>You retain ownership of all content you create in Writers Room.</li>
            <li>You grant us a limited license to store and display your content to operate the service.</li>
            <li>You are responsible for ensuring your content does not violate applicable laws or third-party rights.</li>
          </ul>
        </Section>

        <Section title="AI-Generated Content">
          Responses generated by AI agents within Writers Room are produced by Anthropic's Claude API. We do not guarantee the accuracy, safety, or suitability of AI-generated content. Do not rely on it for legal, medical, or financial decisions.
        </Section>

        <Section title="Prohibited Use">
          You may not use Writers Room to:
          <ul style={{ paddingLeft: 20, lineHeight: 2, marginTop: 8 }}>
            <li>Generate or distribute illegal content.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the service.</li>
            <li>Violate Anthropic's usage policies through the AI features.</li>
          </ul>
        </Section>

        <Section title="Availability">
          We aim for high availability but make no guarantees. The service may be interrupted for maintenance, updates, or circumstances outside our control. We are not liable for any loss resulting from downtime.
        </Section>

        <Section title="Limitation of Liability">
          To the maximum extent permitted by law, Writers Room and its operators are not liable for any indirect, incidental, or consequential damages arising from your use of the service.
        </Section>

        <Section title="Termination">
          We reserve the right to suspend or terminate accounts that violate these terms. You may stop using the service at any time and request deletion of your data.
        </Section>

        <Section title="Changes">
          We may update these terms at any time. Continued use after changes constitutes acceptance.
        </Section>

        <Section title="Contact">
          Questions? Email <a href="mailto:frederic.labadie@willowtreeapps.com" style={{ color: "#4da8ff" }}>frederic.labadie@willowtreeapps.com</a>.
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontFamily: T.mono, fontSize: 11, color: "#4da8ff", letterSpacing: "0.12em", marginBottom: 12 }}>
        {title.toUpperCase()}
      </h2>
      <div style={{ fontSize: 14, lineHeight: 1.75, color: T.body }}>
        {children}
      </div>
    </div>
  );
}
